### ISSUE TITLE
Show "load more" option IF users have 2 or less places nearby.

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/prox#158]
Not a part of the Kona MVP, but given a users' location and our pre-determined radius for "nearby", if they have less than 2 places "nearby", we should allow users to view more places and still get some value from Prox.

The idea here is to have a button that allows users to "load/show more" places by expanding the "nearby" radius by a set amount.

WIP MOCK

![map - too few places](https://cloud.githubusercontent.com/assets/1994820/20192109/4778686a-a73d-11e6-8967-530bfe6ab7dd.png)

**Comment by brampitoyo** [comment]
Some proposed behaviours below:

### Show/hide button

* “Load more” button will appear only if the app has received ≤ 3 places nearby

### Load more button and search radius

* After tapping “Load more”, perform search by an additional 30 minute radius
  * For example, if our initial behaviour is to search for places within an hour, “Load more” should search for places within 90 minutes radius
* If, after performing additional search, the app has received no additional place, perform another search by an additional 30 minutes radius
  * Following the last example, the next automated search should be within 120 minutes radius
* Search radius should stop at 4 hours, or maybe even less
  * If our focus is on giving users the best day possible, we should focus on places that can be reached within half a day’s worth of travelling, at most. Plus, we should allow users some time to enjoy the destination before getting back.

### Time-sensitive search radius

The later in the day you are, the less maximum search radius should go up. This is because, the later in the day you’re going, the less return travel time you’ll have.

Here are some suggested values that we will most certainly have to tweak some more:

* If you search any time from morning to 10am, maximum search radius = 4 hours
* From 10am–12pm, maximum search radius = 3 hours
* From 12pm–3pm, maximum search radius = 2 hours
* From 3pm onwards, maximum search radius = 1 hour (back to normal value)

### When search radius fails

When search has been performed up to maximum search radius, but the app only received ≤ 3 places nearby, what to do here?

There are a few alternatives to think about:

* Widening search categories
  * Maybe show some places under “nightlife” when user searches for activity after 5 pm
* Time-based suggestions for the next day:
  * [I’m an early bird] [I’m a night owl]
  * [I’m an early bird] If you start at 9 am tomorrow, here are places you can go to.
  * [I’m a night owl] If you start at 11 am or noon tomorrow, here are places you can go to.
* Place-based suggestions:
  * Are you planning on going to these places tomorrow? [nearby_town_1], [nearby_town_2], [nearby_town_3]
  * If you’re going to [nearby_town_1], here are some places that you can go to there

**Comment by brampitoyo** [comment]
One of the potential visuals we can create for this is a map that expands when you tap “Load More”.

![kona-load-more-i01](https://cloud.githubusercontent.com/assets/51007/20616309/361aea24-b346-11e6-9902-1916eb3b84ed.gif)

[Full res video](https://d17oy1vhnax1f7.cloudfront.net/items/13111T0k1B0g0e0Q0n09/kona-load-more-i01.mov)

**Comment by antlam** [comment]
We'll likely be working on a new "Map/Alternative view" that will change the UI/UX here. Closing for now.
