### ISSUE TITLE
Implement notification criteria

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/prox#170]
https://docs.google.com/document/d/101jsPjZZ-a_MgZn1UaAyJouufkxzJqG07IrI_0USj1M/edit#heading=h.orhdwaxry889

This criteria determines:

1. When we should start looking for events
2. When general (non-Mozilla) events should be notified
3. When Mozilla events should be notified

**Comment by mcomella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user I want to see the most useful places when I open the app so that I can make better decisions about my next step](https://trello.com/c/IBEHIXNb/149-as-a-user-i-want-to-see-the-most-useful-places-when-i-open-the-app-so-that-i-can-make-better-decisions-about-my-next-step)

**Comment by mcomella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user I want to be notified when a relevant event is starting soon in a location near me so that I can be delighted by things that I would not have thought to look for](https://trello.com/c/XCFZIfuk/108-as-a-user-i-want-to-be-notified-when-a-relevant-event-is-starting-soon-in-a-location-near-me-so-that-i-can-be-delighted-by-thing)

**Comment by fluffyemily** [comment]
@brampitoyo If an event has started, but is <= 4 hours long, how long before the end of the event should we continue to tell people that this event is happening near them

**Comment by brampitoyo** [comment]
@fluffyemily In the criteria document, I have the logic and messaging under the headings “Inside Prox” → “Messaging on event badge”.

There, the logic is:

* If event has reached start time
  * Print “[event_name] is now on.”
* For all event, if event is < 1 hours from end time
  * Print “[event_name] is ending in [minutes_to_end_time]”

So we only tell people that “This event will happen in x minutes” before the event starts. Once it starts, we tell them something different.

Does this help answer your question?

**Comment by fluffyemily** [comment]
@brampitoyo I was questioning the logic for showing an event.

So far we have 
IF (endTime - startTime < 4 hours)
AND (startTime - currentTime = 1 hour)
AND (drivingTime ≤ 1 hour)
THEN notify

and 

IF (endTime - startTime ≥ 4 hours)
AND (endTime - currentTime = 2 hours)
AND (drivingTime ≤ 1 hour)
THEN notify

Does this mean that if the event < 4 hours long we don't notify when the event is running, or do we notify once started but only if there is > 2 hours left?

**Comment by brampitoyo** [comment]
@fluffyemily I saw your logic revision on GDoc, went over it with @antlam and decided that it’s much simpler (no more mucking around with ≤ 4 hours long event, for example). So we’ll use yours – and mine has been deleted from the document.
