### ISSUE TITLE
Auto-open place loop when carousel shows 0 places

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/prox#224]
I managed to get into an auto-open loop. The app showed the carousel with 0 places for a while, then places arrived and the app auto-opened the closest place. On closing the details, the carousel view still showed 0 places and auto-opened the closest place immediately. I had to force close the app to get out of the loop.

**Comment by sleroux** [comment]
I noticed this as well today when working on the transition animation but with more than 0 places. From what I can see, `viewWillAppear` is fired each time we're returned back to the root view (which is correct) but it fires an updatePlaces call every time [1]. In turn, this update sometimes calls openClosest which causes the loop.

Instead of blindly updating the places every time on `viewWillAppear`, we should only update the locations when there was significant location change. I couldn't imagine the places updating often enough to justify being updated every time we return back to the screen.

As a side note, I've also noticed that since we're refresh each time we come back, there's periodically a flicker in the transition animation when the collection view is reloaded.

[1] https://github.com/mozilla-mobile/prox/blob/master/Prox/Prox/PlaceCarousel/PlaceCarouselViewController.swift#L207
