### ISSUE TITLE
Place Carousel Place Overview Cards

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/prox#3]
Create a horizontal scrolling collection of place overview cards for the Place Carousel screen

Each card must have:

* An image
* name
* location
* Yelp Review
* Trip Advisor Review

and optionally

* a place category

See https://mozilla.invisionapp.com/share/DZ8UJYJEQ#/screens/194412517 for details

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Place Carousel](https://trello.com/c/MyRuC1k3/98-place-carousel)

**Comment by antlam** [comment]
Incoming specs @fluffyemily ! I've split it up into multiple images because it just looked too crazy all on one. But, here' are some padding, sizes, and type specs for the Map view. 

Assets to follow.
![spec_map_padding](https://cloud.githubusercontent.com/assets/1994820/19325328/724c2510-907a-11e6-8b17-8424ef19be71.png)
![spec_map_type](https://cloud.githubusercontent.com/assets/1994820/19325327/724b712e-907a-11e6-83a3-b3b599f97d11.png)
![spec_map_sizes](https://cloud.githubusercontent.com/assets/1994820/19325325/72480dae-907a-11e6-9cd7-e67c84e33c7d.png)
![spec_map_reviews](https://cloud.githubusercontent.com/assets/1994820/19325326/72496c8a-907a-11e6-872c-217e47bc35b8.png)

**Comment by antlam** [comment]
Assets! I've made them at 100%. 

On the Home View, they're 30% opacity.

[MVP_assets.zip](https://github.com/mozilla-mobile/prox/files/525575/MVP_assets.zip)

**Comment by antlam** [comment]
Assets! I've made them at 100%.

On the Home View, they're 30% opacity.

[MVP_assets.zip](https://github.com/mozilla-mobile/prox/files/525630/MVP_assets.zip)
