### ISSUE TITLE
alam@mozilla.com on build #495: At Revolver but doesn't show "You're here"

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#316]
Feedback from alam@mozilla.com : At Revolver but doesn't show "You're here"

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583c667f9c663101005748b7/e58b6ea7-6895-4618-b3d0-05a41ff3dcce.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Mon Nov 28 2016 17:43:33 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>56.18481</td></tr><tr><td>Build</td><td>495</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam's 📱 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>70% Unplugged</td></tr><tr><td>Memory free</td><td>161 MB / 1795 MB</td></tr><tr><td>Disk free</td><td>74676 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 495](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583c6cc577ec82010004995a&bnum=495)

**Comment by fluffyemily** [comment]
I wonder if this was due to us getting a location with low horizontal accuracy. Apple's location accuracy can be wildly off sometimes. It is possible that we received a more accurate location once the app was open, but then we would not refresh the UI. 

Something to ponder, do we request an update of travel info based on increased accuracy of a users existing location. Not sure if we can do for Kona though, it would be the sort of change that had lots of hidden edges,

**Comment by mcomella** [comment]
See #433
