### ISSUE TITLE
Design Error States for Map View

### ISSUE THREAD

**Issue by vazquez** [mozilla-mobile/prox#32]
Create error states for:
- 0 locations are found around the user
- Current location not found
- No sunset times available
- No Map available

**Comment by vazquez** [comment]
Related to #23

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user I want to be able to have an enjoyable experience from the app even when there are no places near me so that I continue to open the app despite it occasionally not being useful](https://trello.com/c/PAMC0Pmg/162-as-a-user-i-want-to-be-able-to-have-an-enjoyable-experience-from-the-app-even-when-there-are-no-places-near-me-so-that-i-continu)

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user, I want to have an enjoyable experience in the time it takes to discover the places around me so that I do not quit the app immediately if it takes a while to find relavant information](https://trello.com/c/Y1cwkXeM/163-as-a-user-i-want-to-have-an-enjoyable-experience-in-the-time-it-takes-to-discover-the-places-around-me-so-that-i-do-not-quit-the)

**Comment by vazquez** [comment]
Closing in favour of duplicate #38

**Comment by mcomella** [comment]
@vazquez Did you mean #158 as dupe?

**Comment by mcomella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Loading screen improvements](https://trello.com/c/fed9HUKu/180-prox-starts-like-in-this-screenshot-and-stays-there-for-a-really-long-time-like-30-seconds-after-that-it-switches-to-the-card-vi)

**Comment by vazquez** [comment]
@mcomella – Yes! Closing this issue due to dupe #158
