### ISSUE TITLE
Design Error States for Home View

### ISSUE THREAD

**Issue by vazquez** [mozilla-mobile/prox#38]
What if we can't retrieve:
- Description (from Wikipedia or Yelp)
- Ratings and Reviews
- Images
- URL
- Categories
- Closing Time

We will always be able to retrieve Venue Name and Transportation

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I want to receive an actionable overview of relevant information about places near me, so that my day is not ruined with FOMO](https://trello.com/c/VPWm03rY/49-i-want-to-receive-an-actionable-overview-of-relevant-information-about-places-near-me-so-that-my-day-is-not-ruined-with-fomo)

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user I want to see a useful carousel card even if all the data is not present so that I can continue to the most out of my experience](https://trello.com/c/EmrIgDgb/166-as-a-user-i-want-to-see-a-useful-carousel-card-even-if-all-the-data-is-not-present-so-that-i-can-continue-to-the-most-out-of-my-)

**Comment by vazquez** [comment]
![edge case ui](https://cloud.githubusercontent.com/assets/1119821/19970918/e4cf9442-a1b3-11e6-8c9b-c2f8d27cb4a6.png)

**Comment by mcomella** [comment]
Thoughts:
* What about places without hours? e.g. a beach (which is probably closed at sunset, but yelp doesn't list hours)
* If we don't have a yelp rating, it'd probably be pretty hard to sort the places.
  * I spoke with Emily: we'll only figure out if this is a problem once we do the prioritization ([see trello card](https://trello.com/c/IBEHIXNb/149-as-a-user-i-want-to-see-the-most-useful-places-when-i-open-the-app-so-that-i-can-make-better-decisions-about-my-next-step)), so we won't implement this error state until we finish that card
* We actually won't have the website for a lot of these places :\ (unless we find & insert them by hand, which is a viable option).
  * We need factual places for the websites and not every yelp place has a factual place

**Comment by mcomella** [comment]
We don't handle:
* No yelp reviews available
* No yelp ratings available

But let's postpone those because this data is important to prioritize places (see the previous comment).

I'll get to work on filtering out:
* Places without yelp ratings *and* reviews
* Places without images.

**Comment by mcomella** [comment]
I don't show the place if we're missing either (or both) a yelp rating or a review. This isn't to the mocks, but see above.

**Comment by mcomella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user, I want the places view to handle missing either yelp reviews or yelp ratings (we already handle missing both)](https://trello.com/c/4Xn9BZ37/205-as-a-user-i-want-the-places-view-to-handle-missing-either-yelp-reviews-or-yelp-ratings-we-already-handle-missing-both)

**Comment by vazquez** [comment]
@mcomella – I have updated the image above to address:

- No URL
- No Closing time available

**Comment by mcomella** [comment]
@vazquez The image appears to be missing now – are you sure it's been updated correctly?

**Comment by mcomella** [comment]
@vazquez Another thought – if we're showing places that have events, but the opened hours conflict (e.g. event is happening after the place closes, according to listed hours), what should we show?

**Comment by vazquez** [comment]
@mcomella – Updated the design again to accommodate events that occur when venue is listed as closed!

**Comment by mcomella** [comment]
Still TODO:
* No review count available

Note: Yelp review counts & ratings can't be missing from places (otherwise we can't filter them) so we don't have to handle collapsing the views if ratings or review counts are missing from both of them.

Deferred:
* Event occurring but place listed as closed (deferred to #99)

**Comment by mcomella** [comment]
> No review count available

Check against #121 – this may already be done.

**Comment by mcomella** [comment]
We currently require yelp to have both a rating and a total review count so we'll never see the error states in row 1, slides 3 & 4.

If we have neither a TripAdvisor review count or rating, we display row 1, slide 2 (dimmed, "No data available"). However, we could run into the case where TripAdvisor is missing a rating but not the review count or vice versa.

@vazquez how should we handle this? fwiw, it'd be easiest on the client to just use the row 1, slide 2 "No data available" state.

**Comment by vazquez** [comment]
@mcomella – What about this? I don't want to show "No Data Available" if we have at least 1/2 properties to show users. Let me know if scope is a concern though.

![artboard 2](https://cloud.githubusercontent.com/assets/1119821/20359522/41d0f8ee-abfe-11e6-99f7-863acac0f0e3.png)

**Comment by mcomella** [comment]
Looks reasonable – thanks, Ricardo!
