### ISSUE TITLE
gCal event at wrong location

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/prox#419]
Google calendar has several Hilton Kona events scheduled today. All of them seem to show up at Dona & Toni's Pizza.

Example event https://calendar.google.com/calendar/render?pli=1#eventpage_6%7Ceid-XzcxMTQ4Y3BpOGwwazJiOWs4NTJqMGI5azY1MWs0YjlwNnQzM2liYTM4b3JqOGRwazhoMGplaGhnNmcgbW96aWxsYS5jb21fYXZoOHEzcHVibnI0dWo0MTlhYXVicGF0MmdAZw-1-0-

**Comment by liuche** [comment]
Thanks for bringing this up. This is fallout from the improved events code - because we weren't  getting reliable results from the Yelp API, we're doing a search only based on lat/lng. It's more reliable (slightly), but crap like this is happening (some of the event location names are wrong, but at least the locations are physicially close, rather than complete misses).

I'm adding a script to hard-code our cache to use correctly use Hilton Waikoloa so that it points to the right card and we won't have problems for Hawaii.

**Comment by liuche** [comment]
https://github.com/mozilla-mobile/prox-server/pull/79

**Comment by liuche** [comment]
Closing because fixed on the server.
