### ISSUE TITLE
Add "V1" filtering UI 

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/prox#508]
![home - filter_final](https://cloud.githubusercontent.com/assets/1994820/22708249/71d26d1c-ed2a-11e6-9480-6092ab9910cd.png)

A simple check-box type of functionality to start. This will allow us to layer on more functionality as we get more feedback too.

Assets to come

**Comment by mariapopova0729** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I want to be able to surface different types of places so that I can always get the most relevant information to me](https://trello.com/c/csJcpiPQ/364-i-want-to-be-able-to-surface-different-types-of-places-so-that-i-can-always-get-the-most-relevant-information-to-me)

**Comment by mcomella** [comment]
I recommend implementing with the [PullableView library](https://www.cocoacontrols.com/controls/pullableview). I have [a sample using Swift & constraints](https://github.com/mcomella/PullableView/blob/swift-constraints/PullableView/ZViewController.swift)

**Comment by thebnich** [comment]
@antlam UI mostly ready -- can add assets for the checkbox/+/x/filter button when they're available.

**Comment by antlam** [comment]
[assets_filterUI.zip](https://github.com/mozilla-mobile/prox/files/775492/assets_filterUI.zip)

Assets! Buttons are padded for tap-ability

**Comment by antlam** [comment]
![button_filter](https://cloud.githubusercontent.com/assets/1994820/22953037/4918886c-f2c4-11e6-9249-00ddf5174990.png)
![button_filter 2x](https://cloud.githubusercontent.com/assets/1994820/22953036/4917c346-f2c4-11e6-80f1-25178ce05db9.png)
![button_filter 3x](https://cloud.githubusercontent.com/assets/1994820/22953038/49195404-f2c4-11e6-8cd1-e01854e8e827.png)
![button_map](https://cloud.githubusercontent.com/assets/1994820/22953040/491e4de2-f2c4-11e6-890b-3baaffc403b1.png)
![button_map 2x](https://cloud.githubusercontent.com/assets/1994820/22953039/491b35f8-f2c4-11e6-872f-a9fb199a5636.png)
![button_map 3x](https://cloud.githubusercontent.com/assets/1994820/22953041/492090f2-f2c4-11e6-8fe0-bd3909f3e8bc.png)

Try these @thebnich

**Comment by brampitoyo** [comment]
What happens when you’re in the Home View and tap the ‘filter’ button? The transition looks like this:

![prox-filters-i04](https://cloud.githubusercontent.com/assets/51007/22956350/a4266c5e-f375-11e6-87c0-c734e9f46c1b.gif)

(Though the animation is up to date, the visual design isn’t. Follow the one outlined by @antlam up above).

**Comment by antlam** [comment]
@thebnich updated above ^

**Comment by thebnich** [comment]
Since this PR was getting pretty big and it'd be good to land all these changes ASAP, I didn't finish the animation polish in #508. Opened #526 for a better animation (and any other visual tweaks we need to make).
