### ISSUE TITLE
Hide our current "Map View" button from the top-left

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/prox#509]
On the Home View, we currently have a Map View button, to "reset" the experience as we move forward with these new features such as filtering, I'd suggest we hide it from the Home View for now.

**Comment by mariapopova0729** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I want to be able to surface different types of places so that I can always get the most relevant information to me](https://trello.com/c/csJcpiPQ/364-i-want-to-be-able-to-surface-different-types-of-places-so-that-i-can-always-get-the-most-relevant-information-to-me)

**Comment by thebnich** [comment]
The assets were updated in #525, and we're using that button for the new map view in the next sprint, so I think we're good now.
