### ISSUE TITLE
Add "Filter" button trigger on Home View

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/prox#510]
I'll give the final icon in a bit, filing so I don't forget.

**Comment by antlam** [comment]
<img width="375" alt="screen shot 2017-02-07 at 12 35 57 pm" src="https://cloud.githubusercontent.com/assets/1994820/22710495/64afc9ba-ed32-11e6-9e0b-81d55d951233.png">

I think this is the Funnel icon we should use for now. It looks like a funnel and it coincidentally looks like our funnel/categories list UI too. 💯

**Comment by mariapopova0729** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I want to be able to surface different types of places so that I can always get the most relevant information to me](https://trello.com/c/csJcpiPQ/364-i-want-to-be-able-to-surface-different-types-of-places-so-that-i-can-always-get-the-most-relevant-information-to-me)

**Comment by antlam** [comment]
Updating Visual mock as per the assets from issue #508 

<img width="390" alt="screen shot 2017-02-16 at 6 15 52 pm" src="https://cloud.githubusercontent.com/assets/1994820/23049915/020dec9e-f474-11e6-8d28-3f72b1b522c0.png">

**Comment by thebnich** [comment]
Fixed as part of #525.
