### ISSUE TITLE
Add "Map View" button on top left

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/prox#58]
Hearing from users that navigating to the "Map view"/"carousel" was not intuitive, it seems that reinstating the "Nearby" button (or something similar) we had from our SF Design Sprint makes the most sense.

**Comment by antlam** [comment]
Attaching a WIP of Map View button (in this example, I've also included this "edge card" UI we're looking to use to help show users they can swipe. Just white placeholders, no live data)

![home - map view button](https://cloud.githubusercontent.com/assets/1994820/19749464/06114e50-9b9e-11e6-899d-4616057046c7.png)

**Comment by antlam** [comment]
**Sizing**
![screen shot 2016-10-28 at 2 26 25 pm](https://cloud.githubusercontent.com/assets/1994820/19822898/abd91dc2-9d1a-11e6-9c1a-9dd0edf6c597.png)

**Spacing**
![screen shot 2016-10-28 at 2 26 14 pm](https://cloud.githubusercontent.com/assets/1994820/19822901/b5d79bc8-9d1a-11e6-8f8e-9d5a58ab8aab.png)

**Icon Assets**
[icon_mapview.zip](https://github.com/mozilla-mobile/prox/files/559455/icon_mapview.zip)

**Comment by antlam** [comment]
![screen shot 2016-10-28 at 2 31 46 pm](https://cloud.githubusercontent.com/assets/1994820/19823036/566bde14-9d1b-11e6-8eea-864e6dfdf076.png)

When double digits, we can extend the width to 30 x 20 like so!

**Comment by mcomella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I want to receive an actionable overview of relevant information about places near me, so that my day is not ruined with FOMO](https://trello.com/c/VPWm03rY/49-i-want-to-receive-an-actionable-overview-of-relevant-information-about-places-near-me-so-that-my-day-is-not-ruined-with-fomo)
