### ISSUE TITLE
New background image on Summary Cards

### ISSUE THREAD

**Issue by vazquez** [mozilla-mobile/prox#62]
Based on feedback for User Research, the map background we implemented in Summary Cards confused individuals, as we offered no actionable interaction.

We are changing the background image on Summary Cards to offer a blurred image with a gradient.

![home - ut](https://cloud.githubusercontent.com/assets/1119821/19778267/f4f19f42-9c49-11e6-84ba-1f5f6daeee31.png)

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I want to receive an actionable overview of relevant information about places near me, so that my day is not ruined with FOMO](https://trello.com/c/VPWm03rY/49-i-want-to-receive-an-actionable-overview-of-relevant-information-about-places-near-me-so-that-my-day-is-not-ruined-with-fomo)

**Comment by fluffyemily** [comment]
@vazquez You want this to change according to the currently displayed photo right? What are the details of the gradient?
