### ISSUE TITLE
Change Assets on Summary Card

### ISSUE THREAD

**Issue by vazquez** [mozilla-mobile/prox#71]
We need to change the Walking Person and Clock assets on the Summary Card.

![screenshot 2016-10-31 14 33 19](https://cloud.githubusercontent.com/assets/1119821/19866568/ff6c18b4-9f76-11e6-9c41-a582d67f821c.png)

New assets are:

`icon_walkingdist.png`
`icon_walkingdist@2x.png`
`icon_walkingdist@3x.png`

and 

`icon_times.png`
`icon_times@2x.png`
`icon_times@3x.png`

Assets are available here: https://www.dropbox.com/sh/b30k7wfqerbbb7f/AACdQhl1QKr0MnQyly6KGngSa?dl=0

**Comment by fluffyemily** [comment]
@vazquez we also need updated images for `icon_drivingdist`

**Comment by vazquez** [comment]
So sorry, `icon_drivingdist.png`, `icon_drivingdist@2x.png`, and `icon_drivingdist@3x.png` have been updated in the Assets Folder.

https://www.dropbox.com/sh/b30k7wfqerbbb7f/AACdQhl1QKr0MnQyly6KGngSa?dl=0

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I want to receive an actionable overview of relevant information about places near me, so that my day is not ruined with FOMO](https://trello.com/c/VPWm03rY/49-i-want-to-receive-an-actionable-overview-of-relevant-information-about-places-near-me-so-that-my-day-is-not-ruined-with-fomo)
