### ISSUE TITLE
Image carousel page indicator does not appear on white images

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox#76]
This should have three dots:

![screen shot 2016-11-01 at 15 26 29](https://cloud.githubusercontent.com/assets/759372/19910005/9fb38818-a047-11e6-86cf-42556b768e39.png)

CC @fluffyemily

**Comment by mcomella** [comment]
Relatedly, it's hard to see the grey dots over the image:
![screen shot 2016-11-01 at 15 35 08](https://cloud.githubusercontent.com/assets/759372/19910215/d8adfa62-a048-11e6-93f3-1e90d0ed3829.png)

**Comment by fluffyemily** [comment]
@antlam @vazquez we need someone to take a look at the page indicator colours to ensure that they stand out even when they are against a background of similar colours.

**Comment by mcomella** [comment]
This was improved with #91. @fluffyemily, is that to UX's spec or does this need further iteration?

**Comment by antlam** [comment]
We're taking a look at this now. And it's actually something we were aware of in design as well. 

For the time being, it's not a breaking issue if this UI doesn't work with every image because users are not relying on this to scroll through images. Rather, this is just a hint at how many images are available for this specific card. Once the user sees/scrolls a couple images here, they'd be fine without the indicators too. Especially if we implement things like issue #61 .

**Comment by mcomella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user, I don't want bugs to affect my visual experience](https://trello.com/c/Fvta5fiT/206-as-a-user-i-don-t-want-bugs-to-affect-my-visual-experience)

**Comment by fluffyemily** [comment]
I just tweaked the colours a little here, but the dots were still hard to
see in certain images which is when I pinged UX to take a look.

**Comment by antlam** [comment]
Hm.. the grey looks a bit off. I think the LightGrey here has inherently the same problems as the white. It just depends on what the photo is like really. 

But since we will be iterating on the sketch file that has this in UI in white, can we set it back to white for now so we can continue iterating on this? 😄 @fluffyemily

**Comment by mcomella** [comment]
@antlam Any further thoughts here?

**Comment by antlam** [comment]
@mcomella this isn't high priority for UX ATM. But it could definitely be improved. I think we should keep this issue open but take it off the Sprint 3 milestone.

But we should leave the UI as white/black for the time being. It's not ideal, but changing it to Lightgrey has the same issues as well. So let's revert it back as UX takes some time to think about it some more.

**Comment by mcomella** [comment]
Using the summary card params, shadows help (offset 2 vertical, 5 radius, 0.4 opacity, black color):

![simulator screen shot nov 16 2016 10 05 30](https://cloud.githubusercontent.com/assets/759372/20359367/5d6022d4-abe4-11e6-976b-333e3d3cccc9.png)

![simulator screen shot nov 16 2016 10 08 34](https://cloud.githubusercontent.com/assets/759372/20359440/acf3cd5a-abe4-11e6-8a10-7c3d53054686.png)

However, the unselected dots can be hard to see since they're currently black (0.8 opacity) on black shadow (0.4 opacity) – how do you want to fix that, @antlam ?

**Comment by vazquez** [comment]
@mcomella – For the unselected dots, we currently have:

`black (0.8 opacity)`
`offset 2 vertical, 5 radius, 0.4 opacity, black color`

Instead of black colour, what if we make the shadow white for the unseleced dots? Is that doable?

`black (0.4 opacity)`
`shadow: offset 2 vertical, 5 radius, 0.4 opacity, white color`

Something like this:

<img width="592" alt="screenshot 2016-11-16 13 30 16" src="https://cloud.githubusercontent.com/assets/1119821/20360214/d6521dfc-ac00-11e6-8ca5-75f16700d8ee.png">

**Comment by mcomella** [comment]
@vazquez What do you think?

0.8 opacity:
![simulator screen shot nov 16 2016 13 28 44](https://cloud.githubusercontent.com/assets/759372/20366618/ce4ae026-ac00-11e6-9edc-38c4aaa824fe.png)

0.4 opacity:
![simulator screen shot nov 16 2016 13 29 50](https://cloud.githubusercontent.com/assets/759372/20366629/d64184a6-ac00-11e6-8ea5-dfedf3f66cce.png)

imo, 0.4 looks too dark and 0.8 is too ghostly, but works.

**Comment by vazquez** [comment]
@mcomella – 

![giphy](https://cloud.githubusercontent.com/assets/1119821/20399035/8a1f9762-acbd-11e6-8c88-9a71ae767b7f.gif)


Mike, my bad. White shadows were a bad call. Let's go back to the way things were with the black shadows. However, instead of using the summary card parameters, let's use the "map view" button parameters. The shadows are tighter in the button.

Once we do this, let's call this issue closed. @antlam and I are not too concerned with the carousel dots because of the knowledge-transfer that carousels afford. Once people swipe once, they will swipe always.

When we close this issue, I'll open a new issue to improve the carousel signifiers when we have more time to do something a little bit different.

**Comment by mcomella** [comment]
Post-patch screenshot:
![simulator screen shot nov 17 2016 11 05 16](https://cloud.githubusercontent.com/assets/759372/20403467/c4c87fb2-acb5-11e6-8010-7116d0f56e65.png)
