### ISSUE TITLE
[follow-up] White space on image background on 7+

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox#80]
![simulator screen shot nov 3 2016 11 58 45](https://cloud.githubusercontent.com/assets/759372/19980859/e4db56ca-a1bc-11e6-8e84-65470fabcf92.png)

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I want to receive an actionable overview of relevant information about places near me, so that my day is not ruined with FOMO](https://trello.com/c/VPWm03rY/49-i-want-to-receive-an-actionable-overview-of-relevant-information-about-places-near-me-so-that-my-day-is-not-ruined-with-fomo)
