### ISSUE TITLE
[follow-up] Try disabling vertical scroll bounce on place details

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox#82]
Scrolling between place details can be janky if you scroll down while swiping to the next card – it seems to be caused by the bounce.

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I want to receive an actionable overview of relevant information about places near me, so that my day is not ruined with FOMO](https://trello.com/c/VPWm03rY/49-i-want-to-receive-an-actionable-overview-of-relevant-information-about-places-near-me-so-that-my-day-is-not-ruined-with-fomo)
